"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_1 = require("../controllers/user");
const Auth_1 = require("../midlewares/Auth");
const profile_1 = require("../controllers/profile");
const router = (0, express_1.Router)();
router.get("/user/:id", user_1.getUserById);
router.patch("/useremail/:id", user_1.editEmailUser);
router.patch("/userpassword/:id", user_1.editPasswordUser);
router.get("/users", Auth_1.authenticate, user_1.getUser);
router.get("/suggested", Auth_1.authenticate, user_1.getSuggestedUsers);
router.delete("/delete/:id", user_1.deleteUser);
router.get("/search", Auth_1.authenticate, profile_1.searchUser);
exports.default = router;
